name: Compile Rules to MRS
on:
  push:
    branches:
      - main
    paths:
      - 'my-domen/*.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Mihomo
        run: |
          wget https://github.com/MetaCubeX/mihomo/releases/download/v1.18.9/mihomo-linux-amd64-v1.18.9.gz
          gunzip mihomo-linux-amd64-v1.18.9.gz
          chmod +x mihomo-linux-amd64-v1.18.9

      - name: Compile Rules
        run: |
          mkdir -p output/my-domen
          # Прямые команды компиляции без циклов, чтобы не зависало
          ./mihomo-linux-amd64-v1.18.9 rule-set compile "my-domen/proxy.yaml" "output/my-domen/proxy.mrs"
          ./mihomo-linux-amd64-v1.18.9 rule-set compile "my-domen/direct.yaml" "output/my-domen/direct.mrs"

      - name: Deploy to Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: release
